### ISSUE TITLE
Handle invalid files gracefully.

### ISSUE THREAD

**Issue by ssmereka** [ssmereka/crave#1]
Currently if a file does not have the correct format of

```
module.exports = function(){
  //blah blah blah
};
```

then the loading fill fail with an error that looks like it is craves fault:

```
Scotts-MBP:server ssmereka$ node index.js 
/Users/ssmereka/Documents/Livio/sdl_shaid/example/request_app_permission/server/node_modules/crave/libs/index.js:446
    require(list[i]).apply(_this, _arguments);
                     ^
TypeError: undefined is not a function
    at requireFiles (/Users/ssmereka/Documents/Livio/sdl_shaid/example/request_app_permission/server/node_modules/crave/libs/index.js:446:22)
    at /Users/ssmereka/Documents/Livio/sdl_shaid/example/request_app_permission/server/node_modules/crave/libs/index.js:498:28
    at createListFromCache (/Users/ssmereka/Documents/Livio/sdl_shaid/example/request_app_permission/server/node_modules/crave/libs/index.js:242:3)
    at /Users/ssmereka/Documents/Livio/sdl_shaid/example/request_app_permission/server/node_modules/crave/libs/index.js:492:11
    at saveCache (/Users/ssmereka/Documents/Livio/sdl_shaid/example/request_app_permission/server/node_modules/crave/libs/index.js:111:12)
    at updateDirectoryInCache (/Users/ssmereka/Documents/Livio/sdl_shaid/example/request_app_permission/server/node_modules/crave/libs/index.js:218:3)
    at /Users/ssmereka/Documents/Livio/sdl_shaid/example/request_app_permission/server/node_modules/crave/libs/index.js:402:5
    at /Users/ssmereka/Documents/Livio/sdl_shaid/example/request_app_permission/server/node_modules/crave/libs/index.js:304:15
    at /Users/ssmereka/Documents/Livio/sdl_shaid/example/request_app_permission/server/node_modules/crave/libs/index.js:316:15
    at /Users/ssmereka/Documents/Livio/sdl_shaid/example/request_app_permission/server/node_modules/crave/libs/index.js:383:20
```

So need to look for this and return a helpful error.

**Comment by ssmereka** [comment]
Fixed in v0.0.9
